"""add_experience_and_education_to_users

Revision ID: 1f84f9fa910c
Revises: a1b2c3d4e5f6
Create Date: 2025-10-22 04:13:24.322913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f84f9fa910c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'stage',
               existing_type=sa.VARCHAR(length=25),
               server_default=None,
               existing_nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=25),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('experience', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('education', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'education')
    op.drop_column('users', 'experience')
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=25),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=False)
    op.alter_column('applications', 'stage',
               existing_type=sa.VARCHAR(length=25),
               server_default=sa.text("'SUBMITTED'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
