"""Add promotion notification type

Revision ID: 60273d7c4963
Revises: 78998157548d
Create Date: 2025-09-09 02:17:34.161162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60273d7c4963'
down_revision: Union[str, Sequence[str], None] = '78998157548d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new enum value to existing enum type
    op.execute("ALTER TYPE notificationtype ADD VALUE 'PROMOTION'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type in a real scenario
    pass
    # ### end Alembic commands ###
