"""add_job_description_fields

Revision ID: a99c37818a61
Revises: 64b4e59bf830
Create Date: 2025-09-16 01:41:45.570345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99c37818a61'
down_revision: Union[str, Sequence[str], None] = '64b4e59bf830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('short_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'short_description')
    # ### end Alembic commands ###
