"""add_score_to_applications

Revision ID: e583491ed753
Revises: c9f8e7d6a5b4
Create Date: 2025-12-10 20:48:08.641739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e583491ed753'
down_revision: Union[str, Sequence[str], None] = 'c9f8e7d6a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_notifications_company_read_date'), table_name='notifications')
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('push_tokens_token_key'), 'push_tokens', type_='unique')
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.create_index(op.f('ix_push_tokens_token'), 'push_tokens', ['token'], unique=True)
    op.drop_index(op.f('idx_swipes_user_direction_created'), table_name='swipes', postgresql_where="((direction)::text = 'LEFT'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_swipes_user_direction_created'), 'swipes', ['user_id', 'direction', 'created_at', 'id'], unique=False, postgresql_where="((direction)::text = 'LEFT'::text)")
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.create_index(op.f('ix_push_tokens_token'), 'push_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('push_tokens_token_key'), 'push_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_company_read_date'), 'notifications', ['company_id', 'is_read', 'created_at'], unique=False)
    op.drop_column('applications', 'score')
    # ### end Alembic commands ###
