from sqlalchemy import Column, Integer, String, Float, Boolean, Text, DateTime, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from pgvector.sqlalchemy import Vector
import uuid
from app.core.database import Base


class CandidatePUCProfile(Base):
    __tablename__ = "candidate_puc_profiles"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), unique=True, index=True)
    puc_vector = Column(Vector(47))
    openness = Column(Float)
    conscientiousness = Column(Float)
    extraversion = Column(Float)
    agreeableness = Column(Float)
    emotional_stability = Column(Float)
    big_five_confidence = Column(Float)
    n_ach = Column(Float)
    n_aff = Column(Float)
    n_pow = Column(Float)
    intrinsic_motivation = Column(Float)
    temporal_orientation = Column(Float)
    valence_mean = Column(Float)
    arousal_mean = Column(Float)
    dominance_mean = Column(Float)
    emotional_intelligence = Column(Float)
    error_management_score = Column(Float)
    analytical_thinking = Column(Float)
    cognitive_complexity = Column(Float)
    ttr_score = Column(Float)
    narrative_coherence = Column(Float)
    causal_density = Column(Float)
    locus_control = Column(Float)
    accountability = Column(Float)
    i_we_ratio = Column(Float)
    agency_narrative = Column(Float)
    integrity_score = Column(Float)
    task_orientation = Column(Float)
    motivator_hierarchy = Column(JSONB)
    deal_breakers = Column(JSONB)
    leadership_score = Column(Float)
    collaboration_score = Column(Float)
    written_communication = Column(Float)
    adaptability_score = Column(Float)
    resilience_score = Column(Float)
    narrative_archetype = Column(String(30))
    future_orientation = Column(Float)
    goal_specificity = Column(Float)
    churn_risk = Column(Float)
    preferred_culture = Column(String(50))
    ideal_modality = Column(String(30))
    company_size_preference = Column(String(30))
    management_style_compatible = Column(String(30))
    completeness_score = Column(Float, default=0.0)
    cross_layer_consistency = Column(Float)
    social_desirability_flag = Column(Boolean, default=False)
    confidence_level = Column(String(10), default="low")
    questions_answered = Column(Integer, default=0)
    primary_archetype = Column(String(50))
    archetype_probabilities = Column(JSONB)
    analysis_version = Column(String(10), default="v2.0")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


class CandidateMalaResponse(Base):
    __tablename__ = "candidate_mala_responses"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), index=True)
    question_code = Column(String(5), nullable=False)
    question_block = Column(String(1), nullable=False)
    response_text = Column(Text, nullable=False)
    layer1_sentiment = Column(JSONB)
    layer2_nlp = Column(JSONB)
    layer3_liwc = Column(JSONB)
    layer4_neuro = Column(JSONB)
    layer5_synthesis = Column(JSONB)
    token_count = Column(Integer)
    word_count = Column(Integer)
    language = Column(String(5), default="es")
    quality_score = Column(Float)
    processing_status = Column(String(20), default="pending", index=True)
    processing_error = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


class CompanyOrgProfile(Base):
    __tablename__ = "company_org_profiles"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), unique=True)
    culture_vector = Column(Vector(20))
    e1_culture_text = Column(Text)
    e2_no_fit_text = Column(Text)
    e3_decision_style_text = Column(Text)
    e4_best_hire_text = Column(Text)
    culture_valence = Column(Float)
    affiliation_vs_achievement = Column(Float)
    hierarchy_score = Column(Float)
    management_archetype = Column(String(30))
    org_openness = Column(Float)
    org_conscientiousness = Column(Float)
    org_extraversion = Column(Float)
    org_agreeableness = Column(Float)
    org_stability = Column(Float)
    cultural_deal_breakers = Column(JSONB)
    anti_profile_signals = Column(JSONB)
    analysis_version = Column(String(10), default="v2.0")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


class JobMatchConfig(Base):
    __tablename__ = "job_match_configs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(UUID(as_uuid=True), ForeignKey("jobs.id", ondelete="CASCADE"), unique=True)
    e5_skills_vs_attitude = Column(Text)
    e6_team_description = Column(Text)
    e7_first_90_days = Column(Text)
    e8_success_signal = Column(Text)
    e9_failure_profile = Column(Text)
    req_openness_min = Column(Float, default=0.0)
    req_conscientiousness_min = Column(Float, default=0.0)
    req_extraversion_min = Column(Float, default=0.0)
    req_agreeableness_min = Column(Float, default=0.0)
    req_stability_min = Column(Float, default=0.0)
    ideal_big_five_vector = Column(Vector(5))
    weight_hard = Column(Float, default=0.50)
    weight_soft = Column(Float, default=0.30)
    weight_predictive = Column(Float, default=0.20)
    min_experience_years = Column(Integer, default=0)
    required_education_level = Column(String(30))
    required_languages = Column(JSONB, default=list)
    hard_skills_required = Column(JSONB, default=list)
    hard_skills_desired = Column(JSONB, default=list)
    ideal_archetype = Column(String(50))
    anti_profile_vector = Column(JSONB)
    interview_type = Column(String(20), default="conductual")
    portfolio_required = Column(Boolean, default=False)
    certification_required = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


class MatchScore(Base):
    __tablename__ = "match_scores"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"))
    job_id = Column(UUID(as_uuid=True), ForeignKey("jobs.id"), index=True)
    application_id = Column(UUID(as_uuid=True), ForeignKey("applications.id"))
    total_score = Column(Float)
    confidence_multiplier = Column(Float, default=1.0)
    final_effective_score = Column(Float)
    hard_match_score = Column(Float)
    soft_match_score = Column(Float)
    predictive_match_score = Column(Float)
    skills_coverage = Column(Float)
    experience_score = Column(Float)
    education_score = Column(Float)
    language_score = Column(Float)
    hard_filter_passed = Column(Boolean, default=True)
    big_five_fit = Column(Float)
    mcclelland_culture_fit = Column(Float)
    appraisal_values_fit = Column(Float)
    career_narrative_fit = Column(Float)
    top_strengths = Column(JSONB)
    top_alerts = Column(JSONB)
    interview_guide = Column(JSONB)
    explanation_text = Column(Text)
    recruiter_decision = Column(String(20))
    recruiter_notes = Column(Text)
    decision_at = Column(DateTime(timezone=True))
    calculated_at = Column(DateTime(timezone=True), server_default=func.now())
    recalculated_at = Column(DateTime(timezone=True))


class HiringOutcome(Base):
    __tablename__ = "hiring_outcomes"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    match_score_id = Column(UUID(as_uuid=True), ForeignKey("match_scores.id"))
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"))
    job_id = Column(UUID(as_uuid=True), ForeignKey("jobs.id"))
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id"))
    performance_3m = Column(Float)
    retention_3m = Column(Boolean)
    notes_3m = Column(Text)
    performance_6m = Column(Float)
    retention_6m = Column(Boolean)
    notes_6m = Column(Text)
    was_successful_hire = Column(Boolean)
    tenure_months = Column(Integer)
    failure_reason = Column(String(100))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
